#!/bin/bash

Casks=(
    "1password"
    "alfred"
    "brave-browser"
    "calibre"
    "discord"
    "iterm2"
    "mactex-no-gui"
    "maestral"
    "obs"
    "obs-virtualcam"
    "rectangle"
    "telegram"
    "visual-studio-code"
    "whatsapp"
)

for cask in ${Casks[*]}; do
    echo Installing $cask...
    brew install --cask $cask
done
