#!/bin/bash

brew tap homebrew/autoupdate
brew autoupdate start --upgrade --cleanup

brew update
    git-extras\
    pipx

# Alfred Workflow requirements
# - Spotify Mini Player
brew install php

# pyenv requirements for building Python
brew install openssl readline sqlite3 xz zlib pyenv
