#!/bin/bash

if command -v brew &> /dev/null
then
    echo "Homebrew already installed."
else
    echo "Homebrew not installed. Installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

read -p "Press enter to install brew packages... "
brew bundle --file=~/.dotfiles/setup/Brewfile
