#!/bin/bash

git config --global user.name "Jannis Mainczyk"
if [[ `hostname` == "r11054" ]]; then
git config --global user.email jannis.mainczyk@iis.fraunhofer.de;
else
git config --global user.email jmainczyk@gmail.com;
fi

git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status

git config --global core.editor "code --wait"
git config --global core.excludesfile ~/.dotfiles/src/.gitignore

# publish new branches on push
git config --global push.autoSetupRemote true

# working with submodules
git config --global diff.submodule log
git config --global status.submodulesummary 1
