#!/bin/sh

# move to location of this script, so other commands are relative
# to this location. (e.g. when script is called from different dir)
cd `dirname $0`

cd ../src
for FILE in $(ls -A . | grep "\..*")
do
    ln -sh $PWD/$FILE ~/$FILE && echo "~/$FILE ✔️"
done

cd ../bin
mkdir -p ~/bin
for FILE in $(ls -A . | grep "\..*")
do
    ln -sh $PWD/$FILE ~/bin/$FILE && echo "~/bin/$FILE ✔️"
done

cd ../private
for FILE in $(ls -AF . | grep "\..*")
do
    if [[ $FILE == ".git" ]]; then continue; fi
    if [[ ${FILE:0-1} == "/" ]]; then
        # symlink files from dir into same dir under HOME
        # see https://stackoverflow.com/a/20142456
        target=~/${FILE::${#FILE}-1}
        shopt -s dotglob;
        cp -Rsv $PWD/$FILE $target
        continue
    fi
    ln -sh $PWD/$FILE ~/$FILE && echo "~/$FILE ✔️"
done
