# personal
. ~/.dotfiles/src/python
. ~/.dotfiles/src/pyenv
. ~/.dotfiles/src/git
. ~/.dotfiles/src/ruby
. ~/.dotfiles/src/node
. ~/.dotfiles/src/media
. ~/.dotfiles/src/nav
. ~/.dotfiles/src/locale
. ~/.dotfiles/src/pre-commit
. ~/.dotfiles/src/colors
. ~/.dotfiles/src/direnv
. ~/.dotfiles/private/secrets
