#!/bin/bash

# using a custom completion script .zfunc/_pyenv
# to allow for tab-completion within z4h/fzf
# see https://github.com/pyenv/pyenv/pull/1644
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Create and activate a new virtual environment with latest available
# Python version for project in current directory.
# Usage:
#   $ cd my_project
#   $ pv
#   (my_project) $ _
function pv() {
  if [ -n "$1" ]
  then
    venv_name=$1
  else
    venv_name=`basename $PWD`
  fi
  pyenv virtualenv `pyenv latest 3` "$venv_name" 2> /dev/null
  pyenv shell $venv_name
}

alias pvd='pyenv virtualenv-delete'
